//Arduino uses a variant of the C++ programming language
//To run this code in your Arduino UNO R3 use the Arduino IDE provided in their official website

void setup() {
  // put your setup code here, to run once:
  pinMode(9, OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(9, LOW);
  delay(800);
  digitalWrite(9, HIGH);
  delay(800);
  digitalWrite(9, LOW);
  delay(800);
  digitalWrite(9, HIGH);
  delay(800);
  digitalWrite(9, HIGH);
  delay(800);
  digitalWrite(9, LOW);
  delay(800);
  digitalWrite(9, HIGH);
  delay(800);
  digitalWrite(9, LOW);
  delay(400);
  digitalWrite(9, HIGH);
  delay(400);
  digitalWrite(9, LOW);
  delay(400);
  digitalWrite(9, HIGH);
  delay(400);
  digitalWrite(9, LOW);
  delay(400);
  digitalWrite(9, HIGH);
  delay(400);
  digitalWrite(9, LOW);
  delay(400);
  digitalWrite(9, HIGH);
  delay(1000);
}
